AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 200
  Exclude:
    - test/**

Metrics/ModuleLength:
  Max: 100

Metrics/BlockLength:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/ParameterLists:
  Max: 10

Naming/MethodParameterName:
  AllowedNames:
    - n
    - r
    - g
    - b
    - t
    - x
    - y
    - z
    - l
    - u
    - v
    - h
    - c
    - w
    - c1
    - c2
    - r1
    - g1
    - b1
    - r2
    - g2
    - b2
    - cc

Layout/LineLength:
  Enabled: false

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Style/ArgumentsForwarding:
  Enabled: false
