AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - ext/lipgloss/extconf.rb

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 200
  Exclude:
    - test/**

Metrics/BlockLength:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/ParameterLists:
  Max: 10

Layout/LineLength:
  Exclude:
    - Rakefile
    - test/**

Security/Eval:
  Exclude:
    - Rakefile

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets
